### ISSUE TITLE
Secrets should be masked

### ISSUE THREAD

**Issue by mkrakowitzer** [camelotls/actions-thycotic-ss-integration#3]
It should not be possible for the user to echo secrets into the GitHub actions console. The action should protect the user from being able to do things like this.
```
  - name: Print get_secret_field response
    run: |
      echo "Response is: "
      echo ${{ steps.get_secret_field.outputs.json_out }}
```

Perhaps using below is an option? It might require some different outputs however where the json object has already been parsed as part of the action. 

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#masking-a-value-in-log

We cant rely on our users to do this safely.

**Comment by eechau** [comment]
Feature added
